/**
 * Generate a static browser tools catalog from the compiled browser tools barrel.
 *
 * Dynamically imports platform/mcp-server/dist/browser-tools/index.js to get
 * the actual BrowserToolDefinition objects, extracts { name, description, icon }
 * from each tool, and writes a typed catalog to platform/shared/src/generated/.
 *
 * The generated file is committed to git so tsc --build works without running
 * this script first (fresh clones, IDE support, CI caching). The script serves
 * as both an updater (when tools change) and a verifier (catches drift during build).
 *
 * Usage: tsx scripts/generate-browser-tools-catalog.ts
 */

import { execFileSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const repoRoot = join(import.meta.dirname, '..');
const barrelPath = join(repoRoot, 'platform', 'mcp-server', 'dist', 'browser-tools', 'index.js');
const outDir = join(repoRoot, 'platform', 'shared', 'src', 'generated');
const outPath = join(outDir, 'browser-tools-catalog.ts');

// Verify the compiled barrel exists
try {
  await readFile(barrelPath);
} catch {
  console.error(`Error: ${barrelPath} not found. Run tsc --build first.`);
  process.exit(1);
}

// Dynamic import of the compiled barrel to get actual tool definitions.
// pathToFileURL converts the absolute path to a file:// URL, which is
// required on Windows where bare paths like C:\... are not valid ESM
// specifiers (ERR_UNSUPPORTED_ESM_URL_SCHEME).
const { browserTools } = (await import(pathToFileURL(barrelPath).href)) as {
  browserTools: readonly { name: string; description: string; summary?: string; icon?: string; group?: string }[];
};

/** Escape a string for use inside a single-quoted TypeScript string literal */
const singleQuote = (s: string): string => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

// Extract metadata and sort alphabetically by name
const entries = browserTools
  .map(t => ({
    name: t.name,
    description: t.description,
    ...(t.summary ? { summary: t.summary } : {}),
    icon: t.icon ?? 'globe',
    group: t.group,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

// Build the generated file content
const lines: string[] = [
  '/**',
  ' * Auto-generated by scripts/generate-browser-tools-catalog.ts',
  ' * Source: platform/mcp-server/src/browser-tools/*.ts',
  ' *',
  ' * Do not edit manually — run `npm run generate:browser-tools-catalog` to regenerate.',
  ' */',
  '',
  'export interface BrowserToolMeta {',
  '  readonly name: string;',
  '  readonly description: string;',
  '  /** Short human-readable summary for the UI. Falls back to description if omitted. */',
  '  readonly summary?: string;',
  '  readonly icon: string;',
  '  readonly group?: string;',
  '}',
  '',
  'export const BROWSER_TOOLS_CATALOG: readonly BrowserToolMeta[] = [',
];

for (const entry of entries) {
  lines.push('  {');
  lines.push(`    name: ${singleQuote(entry.name)},`);
  lines.push(`    description: ${singleQuote(entry.description)},`);
  if (entry.summary) lines.push(`    summary: ${singleQuote(entry.summary)},`);
  lines.push(`    icon: ${singleQuote(entry.icon)},`);
  if (entry.group) lines.push(`    group: ${singleQuote(entry.group)},`);
  lines.push('  },');
}

lines.push('];');
lines.push('');

const raw = lines.join('\n');

// Run biome to format the output (handles line wrapping, trailing commas, etc.)
// On Windows, .bin shims are .cmd files that require cmd.exe to execute — use
// shell: true so Node.js invokes the shim via cmd.exe. Falls back to raw content
// if biome is unavailable (e.g., native binary not installed for this platform).
let content: string;
try {
  content = execFileSync(
    join(repoRoot, 'node_modules', '.bin', 'biome'),
    ['format', '--stdin-file-path=generated.ts'],
    {
      input: raw,
      encoding: 'utf-8',
      maxBuffer: 10 * 1024 * 1024,
      shell: process.platform === 'win32',
    },
  );
} catch {
  console.warn('  Warning: biome format failed, using unformatted output');
  content = raw;
}

// Only write if content has changed (avoids unnecessary git diffs)
let existing = '';
try {
  existing = await readFile(outPath, 'utf-8');
} catch {
  // File doesn't exist yet — will be created
}

if (existing === content) {
  console.log(`  browser-tools-catalog.ts is up to date (${entries.length} tools)`);
} else {
  await mkdir(outDir, { recursive: true });
  await writeFile(outPath, content, 'utf-8');
  console.log(`  Generated: browser-tools-catalog.ts (${entries.length} tools)`);
}
